#
# Argon One Fan Configuration
#
# List below the temperature (Celsius) and fan speed (in percent) pairs
# Use the following form:
# min.temperature=speed
#
# Defaults; 10% fan speed when >= 55C, 55% fan speed when >= 60C, 100% fan speed when >= 65C
# 55=10
# 60=55
# 65=100
#
# Always on example, fan will always run at 100%
# 1=100
#
# Type the following at the command line for changes to take effect:
# sudo systemctl restart argononed.service
#
# Start below:
55=10
60=55
65=100